"""WealthDeclaration, PoliticalMilestone, Politician table created

Revision ID: 4bda75546ccf
Revises: a25241d67cbd
Create Date: 2026-08-03 20:03:16.102376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bda75546ccf'
down_revision: Union[str, Sequence[str], None] = 'a25241d67cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
