"""daily rose and slap count tables

One row per politician per day, per verdict side. Identity is the pair
(politician_type, politician_id): ids repeat across chief_ministers (1..31) and
ministers (1..90), so the type is what keeps two different people out of the
same row. See app/db/model/daily_counts.py for why this is not an FK to
politicians.id.

Revision ID: 5bb8eb56aae8
Revises: 4bda75546ccf
Create Date: 2026-08-08 22:39:39.487310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb8eb56aae8'
down_revision: Union[str, Sequence[str], None] = '4bda75546ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rose_count_today',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_type', sa.String(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("politician_type in ('cm', 'union_minister', 'mp')", name='ck_rose_count_today_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_type', 'politician_id', 'date', name='uq_rose_count_today_day')
    )
    op.create_index(op.f('ix_rose_count_today_date'), 'rose_count_today', ['date'], unique=False)
    op.create_table('slap_count_today',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_type', sa.String(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("politician_type in ('cm', 'union_minister', 'mp')", name='ck_slap_count_today_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_type', 'politician_id', 'date', name='uq_slap_count_today_day')
    )
    op.create_index(op.f('ix_slap_count_today_date'), 'slap_count_today', ['date'], unique=False)

    # Autogenerate also proposed dropping `political_milestones.position_title_hindi`
    # and indexing `wealth_declarations.declaration_type`. Both are pre-existing
    # drift between the models and the live database, unrelated to this change,
    # and the drop would destroy a populated column — removed by hand.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slap_count_today_date'), table_name='slap_count_today')
    op.drop_table('slap_count_today')
    op.drop_index(op.f('ix_rose_count_today_date'), table_name='rose_count_today')
    op.drop_table('rose_count_today')
    # ### end Alembic commands ###
