"""mp political milestone table

Revision ID: 6e29aea7ab01
Revises: e559407de90e
Create Date: 2026-08-08 23:48:44.270015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e29aea7ab01'
down_revision: Union[str, Sequence[str], None] = 'e559407de90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_political_milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('position_title', sa.Text(), nullable=False),
    sa.Column('position_rank', sa.Integer(), nullable=False),
    sa.Column('election_type', sa.Text(), nullable=True),
    sa.Column('entry_mode', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_political_milestone_mp_id'), 'mp_political_milestone', ['mp_id'], unique=False)
    # Declared here rather than on the model: `mps` is reflected at runtime, so
    # SQLAlchemy has no table object to resolve the reference against at import
    # time. CASCADE so milestones cannot outlive the MP they describe.
    op.create_foreign_key(
        'fk_mp_political_milestone_mp', 'mp_political_milestone', 'mps',
        ['mp_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mp_political_milestone_mp', 'mp_political_milestone', type_='foreignkey')
    op.drop_index(op.f('ix_mp_political_milestone_mp_id'), table_name='mp_political_milestone')
    op.drop_table('mp_political_milestone')
    # ### end Alembic commands ###
