"""mps_hindi localisation table

Revision ID: e559407de90e
Revises: 5bb8eb56aae8
Create Date: 2026-08-08 22:53:55.781498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e559407de90e'
down_revision: Union[str, Sequence[str], None] = '5bb8eb56aae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mps_hindi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('constituency', sa.Text(), nullable=True),
    sa.Column('name_hindi', sa.Text(), nullable=True),
    sa.Column('state_hindi', sa.Text(), nullable=True),
    sa.Column('constituency_hindi', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', name='uq_mps_hindi_mp')
    )
    op.create_index(op.f('ix_mps_hindi_mp_id'), 'mps_hindi', ['mp_id'], unique=False)
    # Declared here rather than on the model: `mps` is reflected at runtime, so
    # SQLAlchemy has no table object to resolve the reference against at import
    # time. CASCADE so a Hindi row can never outlive the MP it translates.
    op.create_foreign_key(
        'fk_mps_hindi_mp', 'mps_hindi', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mps_hindi_mp', 'mps_hindi', type_='foreignkey')
    op.drop_index(op.f('ix_mps_hindi_mp_id'), table_name='mps_hindi')
    op.drop_table('mps_hindi')
    # ### end Alembic commands ###
